services:
  - type: web
    name: portfolio-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://chetanpawar-portfolio-using-react.onrender.com
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
